<?php
// Generated by CI from GitHub Secrets — do not edit on server directly.
define('PAYU_KEY',      '%%PAYU_KEY%%');
define('PAYU_SALT',     '%%PAYU_SALT%%');
define('PAYU_MID',      '%%PAYU_MID%%');
define('PAYU_MODE',     'live');
define('PAYU_ENDPOINT', 'https://secure.payu.in/_payment');

function payuBaseUrl(): string {
    $scheme = (!empty($_SERVER['HTTPS']) && $_SERVER['HTTPS'] !== 'off') ? 'https' : 'http';
    $host   = $_SERVER['HTTP_HOST'] ?? 'localhost';
    return $scheme . '://' . $host . '/backend';
}

function payuRequestHash(array $p): string {
    $seq = [
        $p['key'] ?? '', $p['txnid'] ?? '', $p['amount'] ?? '', $p['productinfo'] ?? '',
        $p['firstname'] ?? '', $p['email'] ?? '',
        $p['udf1'] ?? '', $p['udf2'] ?? '', $p['udf3'] ?? '', $p['udf4'] ?? '', $p['udf5'] ?? '',
        '', '', '', '', '', PAYU_SALT,
    ];
    return strtolower(hash('sha512', implode('|', $seq)));
}

function payuResponseHash(array $r): string {
    $seq = [
        PAYU_SALT, $r['status'] ?? '',
        '', '', '', '', '',
        $r['udf5'] ?? '', $r['udf4'] ?? '', $r['udf3'] ?? '', $r['udf2'] ?? '', $r['udf1'] ?? '',
        $r['email'] ?? '', $r['firstname'] ?? '', $r['productinfo'] ?? '',
        $r['amount'] ?? '', $r['txnid'] ?? '', $r['key'] ?? '',
    ];
    return strtolower(hash('sha512', implode('|', $seq)));
}
