<?php
// matrimony/backend/sms.php — generated by deploy workflow from GitHub Secrets
// Template: sms.template.php (committed). Real credentials injected at deploy time.

define('SMS_ENABLED',     true);
define('SMS_API_URL',     'https://www.smsidea.co.in/smsstatuswithid.aspx');
define('SMS_USERNAME',    '%%SMS_USERNAME%%');
define('SMS_API_KEY',     '%%SMS_API_KEY%%');
define('SMS_SENDER_ID',   '%%SMS_SENDER_ID%%');
define('SMS_DLT_TE_ID',   '%%SMS_DLT_TE_ID%%');

// OTP Message template — must match DLT registered content exactly
define('SMS_OTP_TEMPLATE', 'Your Login OTP {OTP} Chennai-Pondicherry Matrimony.-for More info-call- +91 72001 64409');

function sendSMS(string $mobile, string $message): array {
    if (!SMS_ENABLED) {
        return ['success' => true, 'response' => 'SMS disabled (demo mode)', 'error' => null];
    }

    $to = $mobile;
    if (strlen($to) === 10) {
        $to = '91' . $to;
    }

    $fields_string = 'mobile=' . SMS_USERNAME
        . '&pass=' . SMS_API_KEY
        . '&senderid=' . SMS_SENDER_ID
        . '&to=' . $to
        . '&msg=' . rawurlencode($message);

    if (defined('SMS_DLT_TE_ID') && SMS_DLT_TE_ID) {
        $fields_string .= '&TemplateID=' . SMS_DLT_TE_ID;
    }

    try {
        $ch = curl_init();
        curl_setopt($ch, CURLOPT_URL, SMS_API_URL);
        curl_setopt($ch, CURLOPT_POST, true);
        curl_setopt($ch, CURLOPT_POSTFIELDS, $fields_string);
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
        curl_setopt($ch, CURLOPT_TIMEOUT, 15);
        curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);

        $response = curl_exec($ch);
        $httpCode = curl_getinfo($ch, CURLINFO_HTTP_CODE);
        $error    = curl_error($ch);
        curl_close($ch);

        if ($error) {
            error_log("SMS API cURL error: $error");
            return ['success' => false, 'response' => '', 'error' => "SMS send failed: $error"];
        }

        $response = trim($response);
        error_log("SMS API response for $mobile: $response (HTTP $httpCode)");

        $hasError = (stripos($response, 'error') !== false);
        $hasFail  = (stripos($response, 'fail') !== false);

        if ($httpCode === 200 && $response && !$hasError && !$hasFail) {
            return ['success' => true, 'response' => $response, 'error' => null];
        }

        return ['success' => false, 'response' => $response, 'error' => "SMS API returned: $response"];

    } catch (Exception $e) {
        error_log("SMS exception: " . $e->getMessage());
        return ['success' => false, 'response' => '', 'error' => $e->getMessage()];
    }
}

function sendOTP(string $mobile, string $otp): array {
    $message = str_replace('{OTP}', $otp, SMS_OTP_TEMPLATE);
    $result  = sendSMS($mobile, $message);

    if (!$result['success']) {
        error_log("OTP send failed for $mobile: " . ($result['error'] ?? 'Unknown error'));
    }

    return $result;
}
